ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-kafka-acl-producer_{context}']
= rhoas kafka acl producer

[role="_abstract"]
Add ACL rules for user to produce messages to topics

[discrete]
== Synopsis

This command will create ACL rules to allow user to produce messages to topics

....
rhoas kafka acl producer [flags]
....

[discrete]
== Examples

....
# Grant access to principal to allow producing messages to all topics
$ rhoas kafka acl producer --user user_name

# Grant access to principal to allow producing messages to topics starting with "abc"
$ rhoas kafka acl producer --user user_name --topic-prefix "abc"

....

[discrete]
== Options

      `--service-account` _string_::    service account ID to be used as principal
      `--topic-prefix` _string_::       prefix topic name to define ACL rules for
      `--transactional-id` _string_::   transactional ID for which ACL rules are to be defined
      `--user` _string_::               username to be used as principal

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_kafka_acl.adoc#rhoas-kafka-acl[rhoas kafka acl]	 - Kafka ACL management for users and service accounts
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-kafka-acl_{context}[rhoas kafka acl]	 - Kafka ACL management for users and service accounts
endif::[]

